%Floyd Ëã·¨µÄMatlab
W = [0, 20, 15, inf, inf, inf, inf; inf, 0, inf, 8, 24, inf, inf; ...
inf, inf, 0, 10, inf, 6, inf; inf, inf, inf, 0, 10, 8, inf; ...
inf, inf, inf, inf, 0, inf, 11; inf, inf, inf, inf, inf, 0, 20; ...
inf, inf, inf, inf, inf, inf, inf];
[P, u] = f_path(W)